import type { Metadata } from "next";
import localFont from "next/font/local";

import { QueryProvider } from '@/providers';
import { Menu } from '@/components';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className={`flex h-screen overflow-hidden`}>
            <aside className={'w-1/5 py-4 h-screen px-2 border-r'}>
              <nav aria-label="Courses list">
                <Menu />
              </nav>
            </aside>
            <main className={'w-full h-screen overflow-y-scroll px-4 py-10'}>
              {children}
            </main>
          </div>
        </body>
      </html>
    </QueryProvider>
  );
}
